# Generated by Django 4.2.29 on 2026-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('upload', 'File Upload'), ('url', 'Image URL')], max_length=10)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='detections/input/')),
                ('input_image_url', models.URLField(blank=True, null=True)),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='detections/output/')),
                ('pothole_count', models.PositiveIntegerField(default=0)),
                ('detections_json', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Inference time in seconds', null=True)),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
